- examples/components/alert_example.py
> Add alert example component

- examples/embed_example.py
- uix_demo2.py
> Add embed_example and update TODO list

- examples/components/credit_card_example.py
> Add credit card component example

- examples/components/imagecard_example.py
> Refactor imagecard_example.py

- uix_demo.css
- uix_demo.py
> Mini optimization

- uix_demo.py
> elements ve components tek fonksiyon, hepsi sıralı çağrılıyor

- examples/components/basic_tree_example.py
> Add basic_tree_example.py to examples/components

- uix_demo.css
- uix_demo.py
> Optimizasyon + Filtre

- examples/components/address_form_example.py
- examples/components/basic_datalist_example.py
> addressform example ekledi ve basicdatalist example'a dictionary eklendi

- examples/components/basic_slider_example.py
> basic slider example update

- examples/components/address_form_example.py
> Add getformdata callback to address_form_example.py

- examples/button_example.py
- examples/components/tooltip_example.py
- examples/icon_example.py
> tooltip example, icon exam

- examples/image_viewer_example.py
> Update image viewer button group

- examples/page_example.py
- uix_demo.css
- uix_demo.py
> uix-demo css edited

- examples/input_example.py
> input example görünümü düzenlendi

- examples/components/toggle_checkbox_example.py
> toggle checkbox example eklendi

- examples/components/alert_example.py
> Refactor alert_example.py to add multiple alert types

- examples/table_example.py
> Table example iyileştirildi.

- examples/components/chart_bar_example.py
> Add chart_bar_example.py

- examples/components/chart_line_example.py
> Add chart_line_example.py

- examples/components/chart_scatter_example.py
> Add scatter chart example

- examples/components/chart_pie_example.py
> Add chart_pie_example.py

- examples/components/alert_example.py
> Refactor alert_example.py

- uix_demo.py
> Elemanların bulunduğu menüde en alt eleman gözükmüyordu. FIX.

- examples/components/address_form_example.py
- locale/tr.json
> Add language change functionality and update localization

- examples/file_example.py
> Update file_example.py imports

- examples/form_example.py
@hozgur  #42 sorunu bu request ile çözüldü
> Add form submission functionality to form_example.py

- route_test.py
- uix_demo.css
> route yapısı için test dosyası hazırlandı

- examples/components/input_image_example.py
- examples/components/input_output_image_example.py
- examples/components/output_image_example.py
> input, output ve ikisinin birlikte kullanıldığı örnekler eklendi

- examples/components/cropper_dialog_example.py
- examples/components/prompt_example.py
> Add cropper dialog example

- examples/api_example.py
> Refactor API example code and update image paths

- examples/components/input_output_image_example.py
> yeni set_image fonksiyonuna göre demo güncellendi

- examples/components/basic_tree_example.py
> Refactor basic_tree_example.py to include a nested data structure in the Tree View component

- examples/components/tooltip_example.py
> tooltip example geliştirme

- examples/components/chart_bar_example.py
- examples/components/chart_line_example.py
> Add dataset colors to chart options in examples

- examples/components/basic_table_example.py
- examples/components/loading_example.py
- examples/input_example.py
> Table comp. example eklendi. Loading, input example update

- examples/components/md_playground_example.py
- uix_demo.py
> search area update

- examples/components/data_table_example.py
> datatable example added

- examples/components/data_table_example.py
> data_table example güncellendi
